# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jordyn/Code/qtfm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jordyn/Code/qtfm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jordyn/Code/qtfm/CMakeFiles /home/jordyn/Code/qtfm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jordyn/Code/qtfm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qtfm

# Build rule for target.
qtfm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qtfm
.PHONY : qtfm

# fast build rule for target.
qtfm/fast:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/build
.PHONY : qtfm/fast

#=============================================================================
# Target rules for targets named qtfm_autogen

# Build rule for target.
qtfm_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qtfm_autogen
.PHONY : qtfm_autogen

# fast build rule for target.
qtfm_autogen/fast:
	$(MAKE) -f CMakeFiles/qtfm_autogen.dir/build.make CMakeFiles/qtfm_autogen.dir/build
.PHONY : qtfm_autogen/fast

fileviewwidget.o: fileviewwidget.cpp.o

.PHONY : fileviewwidget.o

# target to build an object file
fileviewwidget.cpp.o:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/fileviewwidget.cpp.o
.PHONY : fileviewwidget.cpp.o

fileviewwidget.i: fileviewwidget.cpp.i

.PHONY : fileviewwidget.i

# target to preprocess a source file
fileviewwidget.cpp.i:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/fileviewwidget.cpp.i
.PHONY : fileviewwidget.cpp.i

fileviewwidget.s: fileviewwidget.cpp.s

.PHONY : fileviewwidget.s

# target to generate assembly for a file
fileviewwidget.cpp.s:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/fileviewwidget.cpp.s
.PHONY : fileviewwidget.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

qtfm_autogen/mocs_compilation.o: qtfm_autogen/mocs_compilation.cpp.o

.PHONY : qtfm_autogen/mocs_compilation.o

# target to build an object file
qtfm_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/qtfm_autogen/mocs_compilation.cpp.o
.PHONY : qtfm_autogen/mocs_compilation.cpp.o

qtfm_autogen/mocs_compilation.i: qtfm_autogen/mocs_compilation.cpp.i

.PHONY : qtfm_autogen/mocs_compilation.i

# target to preprocess a source file
qtfm_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/qtfm_autogen/mocs_compilation.cpp.i
.PHONY : qtfm_autogen/mocs_compilation.cpp.i

qtfm_autogen/mocs_compilation.s: qtfm_autogen/mocs_compilation.cpp.s

.PHONY : qtfm_autogen/mocs_compilation.s

# target to generate assembly for a file
qtfm_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/qtfm_autogen/mocs_compilation.cpp.s
.PHONY : qtfm_autogen/mocs_compilation.cpp.s

sidebar/widgets/mimetype.o: sidebar/widgets/mimetype.cpp.o

.PHONY : sidebar/widgets/mimetype.o

# target to build an object file
sidebar/widgets/mimetype.cpp.o:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/sidebar/widgets/mimetype.cpp.o
.PHONY : sidebar/widgets/mimetype.cpp.o

sidebar/widgets/mimetype.i: sidebar/widgets/mimetype.cpp.i

.PHONY : sidebar/widgets/mimetype.i

# target to preprocess a source file
sidebar/widgets/mimetype.cpp.i:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/sidebar/widgets/mimetype.cpp.i
.PHONY : sidebar/widgets/mimetype.cpp.i

sidebar/widgets/mimetype.s: sidebar/widgets/mimetype.cpp.s

.PHONY : sidebar/widgets/mimetype.s

# target to generate assembly for a file
sidebar/widgets/mimetype.cpp.s:
	$(MAKE) -f CMakeFiles/qtfm.dir/build.make CMakeFiles/qtfm.dir/sidebar/widgets/mimetype.cpp.s
.PHONY : sidebar/widgets/mimetype.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... qtfm"
	@echo "... edit_cache"
	@echo "... qtfm_autogen"
	@echo "... fileviewwidget.o"
	@echo "... fileviewwidget.i"
	@echo "... fileviewwidget.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... qtfm_autogen/mocs_compilation.o"
	@echo "... qtfm_autogen/mocs_compilation.i"
	@echo "... qtfm_autogen/mocs_compilation.s"
	@echo "... sidebar/widgets/mimetype.o"
	@echo "... sidebar/widgets/mimetype.i"
	@echo "... sidebar/widgets/mimetype.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

